app/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    # path("reservations/", include("reservations.urls", namespace="reservations")),
    # path("reviews/", include("reviews.urls", namespace="reviews")),
    # path("lists/", include("lists.urls", namespace="lists")),
    # path("conversations/", include("conversations.urls", namespace="conversations")),
    # re_path(r'^', include('app.urls')),

    # re_path(r'^static/(?P<path>.*)$', serve,
    #         {'document_root': settings.STATIC_ROOT}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("sigup/", views.SignUpView.as_view(), name="signup"),
    # path("login/github/", views.github_login, name="github-login"),
    # path("login/github/callback/", views.github_callback, name="github-callback"),
    # path("login/kakao/", views.kakao_login, name="kakao-login"),
    # path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    # path("verify/<str:key>/", views.complete_verification, name="complete-verification"
    # ),
    # path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    # path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    # path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    # path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    # path("switch-language/", views.switch_language, name="switch-language"),
]

templates/partials/nav.html
{% load i18n %}
<ul class="flex items-center text-sm font-medium h-full">
    {% if user.is_authenticated %}
        <li class="nav_link">
            {% comment %} <a href="{% url 'users:switch-hosting' %}"> {% endcomment %}
                {% if request.session.is_hosting %}
                    {% trans "Stop hosting" %}
                {% else %}
                    {% trans "Start hosting" %}
                {% endif %}
            {% comment %} </a> {% endcomment %}
        </li>
        {% if request.session.is_hosting %}
            <li class="nav_link"><a href="{% url 'rooms:create' %}">{% trans "Create Room" %}</a></li>
        {% endif %}
        {% comment %} <li class="nav_link"><a href="{% url 'lists:see-favs' %}">{% trans "Favs" %} ({{user.list.rooms.count}})</a></li> {% endcomment %}
        <li class="nav_link"><a href="{{user.get_absolute_url}}">{% trans "Profile" %}</a></li>
        <li class="nav_link"><a href="{% url "users:logout" %}" class="bg-indigo-400 px-4 rounded text-white mx-2  py-3">{% trans "Log out" %}</a></li>
    {% else %}
        <li class="nav_link" ><a href="{% url "users:login" %}" class="bg-indigo-400 px-4 py-3 rounded text-white mx-2">{% trans "Log in" %}</a></li>
        <li class="nav_link"><a href="{% url "users:signup" %} " class="bg-indigo-400 px-4 rounded text-white mx-2  py-3">{% trans "Sign up" %}</a></li>
    {% endif %}
</ul>