app/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    # path("reservations/", include("reservations.urls", namespace="reservations")),
    # path("reviews/", include("reviews.urls", namespace="reviews")),
    # path("lists/", include("lists.urls", namespace="lists")),
    # path("conversations/", include("conversations.urls", namespace="conversations")),
    # re_path(r'^', include('app.urls')),

    # re_path(r'^static/(?P<path>.*)$', serve,
    #         {'document_root': settings.STATIC_ROOT}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    # path("create/", views.CreateRoomView.as_view(), name="create"),
    # path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    # path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    # path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    # path(
    #     "<int:room_pk>/photos/<int:photo_pk>/delete/",
    #     views.delete_photo,
    #     name="delete-photo",
    # ),
    # path(
    #     "<int:room_pk>/photos/<int:photo_pk>/edit/",
    #     views.EditPhotoView.as_view(),
    #     name="edit-photo",
    # ),
]

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block page_title %}{% endblock page_title %}| SE PROJ.</title>
</head>
<body class="text-gray-800 mt-24 font-light">
	<header class="container max-w-full inset-0 flex items-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white">
		<div class="flex items-center">
			<a href="{% url 'core:home' %}">
				FASTRent
			</a>
				  {% block search-bar %}
				<form action="{% url 'rooms:search' %}" method="get" >
					<input name='city' placeholder="Search By City" class="border border-gray-200 mx-4 p-2 rounded">
				</form>
				{% endblock search-bar %}
		</div>
      {% include "partials/nav.html" %}

	</header>


	{% block content %}
	{% endblock content %}
</body>
</html>